name: Run Tests
description: Run Tests

inputs:
  ctest:
    description: Path to CTest executable
    required: True
  test-dir:
    description: Path to test directory
    required: True
  jobs:
    description: Number of jobs to use
    default: 1
  config:
    description: CTest configuration to test
    default: RelWithDebInfo

runs:
  using: composite
  steps:
    - uses: nick-fields/retry@v2
      with:
        shell: pwsh
        retry_on: error
        timeout_minutes: 20
        command: |
          & '${{ inputs.ctest }}' --test-dir '${{ inputs.test-dir }}' -C ${{ inputs.config }} -V -j${{ inputs.jobs }}
